### ISSUE TITLE
[1.9.4] ConcurrentModificationException

### ISSUE THREAD

**Issue by Claycorp** [elix-x/Avoid-Exploding-Creepers#4]
Crash log: http://pastebin.com/vezHhfTg
Log with ASM information: http://pastebin.com/d84MyXXT
I know this is the same issue as #1 and #2 but thought I would open another issue as it is still an issue in 1.9.4 Also they did not include the ASM information from the log that might help pinpoint the issue.

**Comment by Elix-x** [comment]
Sadly, i don't know what causes it. It is very random, and when you relog, it's gone. It may return once in a while, but it is extremely random.
Only thing i can do (and will for 1.10.2) is to add try-catch so it doesn't crash the game, but simply fails to compute affected entities.

**Comment by Claycorp** [comment]
This was on a server just FYI. I know it doesn't really change anything but thought I'd share that info. I really can't say much more than that as I just manage the server and have no idea what happened exactly. Just happened to see the server was down and something happened.

**Comment by Elix-x** [comment]
As i said, it's extremely random and happens in both SP and MP. Personally, i think i've never met it myself.

**Comment by dries007** [comment]
Try replacing the `new HashMap` with a `new ConcurrentHashMap` in ExplosionSrcManager, it is happening because you are sharing a map between the worlds and server tick methods, which can get called in separate threads, thus causing a ConcurrentModificationException. A ConcurrentHashMap should be able to cope with that, but (without having read any deeper then just the ExplosionSrcManager) I don't understand why you have 1 shared global map for something that seems like it should be on a per world basis.

**Comment by Elix-x** [comment]
Crash is on line [131](https://github.com/elix-x/Creeper-Awareness/blob/master/1.10/src/main/java/code/elix_x/mods/creeperawareness/api/ExplosionSrcManager.java#L131), where i iterate over list of entities in world... Can't change that to concurent list.

**Comment by dries007** [comment]
I misread, sorry. (Though I think it'd still be a good idea regardless)
You could potentially use a `ImmutableList.copyOf(world.loadedEntityList)` +`for loop instead of an iterator.

**Comment by Elix-x** [comment]
`ImmutableList.copyOf(world.loadedEntityList)` => --performance
`for` => https://github.com/elix-x/Creeper-Awareness/commit/1bc1db1c306a984efe33c4ab5dfb9445fb0015a9#diff-72e74a2707bee208df71922c0ea96797L129

**Comment by dries007** [comment]
Well, I'd say --preformance > crashing :smile: 
And you should only use the for if you are doing the immutablelist.
One of the only other things I can come up with is that and event listener for `GetExplosionSourceFromEntityEvent` is modifying the `loadedEntityList`. (Which you can't really avoid, without using some immutable collection, unless you cache the events until after the loop end then emit them at mass.)

**Comment by Elix-x** [comment]
Well. I thought of simply using `try catch`...
How does `GetExplosionSourceFromEntityEvent` modify `loadedEntityList`? It is [posted](https://github.com/elix-x/Creeper-Awareness/blob/master/1.10/src/main/java/code/elix_x/mods/creeperawareness/api/ExplosionSrcManager.java#L139) inside loop and has only an entity and explosion source to be set as fields.

**Comment by dries007** [comment]
If anyone listening to GetExplosionSourceFromEntityEvent removes the entity from the world, it would crash on your code, not theirs for example.
Try-catching here would be unwise IMO. It doesn't fix the issue, and it would also (if my thoughts about the even listener are correct) not inform or warn the  even listeners not to modify the entity list. (It's not quite proper to impose that limit to your API users, simply because you can count on it most people won't follow that.)

**Comment by Elix-x** [comment]
1. And why would somebody remove an entity from world when he is asked to provide explosion source?
2. I don't know anybody who uses this API besides me...

EDIT: And `try catch` > `--preformance` > crash

**Comment by dries007** [comment]
Who knows... Someone may be catching all EntityEvents and doing some modifications based on that.
I wonder what the performance penalty of `try-catch` vs `ImmutableList` vs a second loop to emit events is.

**Comment by Elix-x** [comment]
Try and catch in java are heavy operations.
`ImmutableList` will convert list to array and then build from array. If world has many entities, performance hit will be very important.
Emitting event later won't help, as it would be equivalent of `ImmutableList` - entities have to be stored somewhere in order to be reused.

I may have found something that may work:

``` java
for(int i = 0; i < world.loadedEntityList.size(); i++){
            Entity entity = world.loadedEntityList.get(i);
```

**Comment by dries007** [comment]
Well, would the emit later list not be a lot smaller then the main entity list since the event is only emitted if there is no data yet?
Thinking about that, would it not be possible to do this event on EntityJoinWorld (or whatever that is called, i don't have my dev env here).
I think such a loop is in bytecode equivalent to the normal for loop, if nothing gets done with i during the loop body. Can't be sure though.

**Comment by Elix-x** [comment]
> Well, would the emit later list not be a lot smaller then the main entity list since the event is only emitted if there is no data yet?

No. It will be reemitted for each pig each time.

> Thinking about that, would it not be possible to do this event on EntityJoinWorld (or whatever that is called, i don't have my dev env here).

Nope. Creepers aren't exploding until they are.

> I think such a loop is in bytecode equivalent to the normal for loop, if nothing gets done with i during the loop body. Can't be sure though.

`for(O o : list)` == `for(Iterator it = list.iterator(); it.hasNext();) O o = it.next();`

**Comment by dries007** [comment]
Oh yea, that all makes sense. I'd say use the integer based for loop. That seems like the best option.

**Comment by Elix-x** [comment]
I'll do this for 1.10.2 version. Everybody can easily upgrade from 1.9.4 anyways.
